### ISSUE TITLE
Implement MySQL Data Replication Solution

### ISSUE THREAD

**Issue by qiaofeng1227** [websoft9dev/role_mysql#12]
Premise: The data of the two MySQL database servers have been synchronized or completely consistent,
What extra preparations should MySQL server to do for dynamic and static separation?

support version: mysql8.0

content：Write two shell scripts respectively and execute them on the master-slave server. After execution, the master-slave synchronization can be realized. The required server IP and other variables are passed into the script in the form of parameters

**Comment by natk9** [comment]
Delete operations related to uuid in the script before test.（mysql requires uuid to be consistent）

mysql version：5.7、8.0
system：centos、ubuntu
centos-mysql5.7、centos-mysql8.0、ubuntu-mysql5.7 can run success
ubuntu-mysql8.0 Report  error
error:
Slave_IO_Running : no
Last_IO_Error: error connceting to master 'slave@40.78.148.57:3306'  - retry-time: 60 retries: 1 message: Authentication plugin 'caching_sha2_password' reported error: Authentication requires secure connection.
about  caching_sha2_password
can access  https://www.modb.pro/db/29919
alter error
ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '123456';
FLUSH PRIVILEGES;

Execute again the slave.sh
error:
Last_IO_Error: Fatal error: The slave I/O thread stops because master and slave have equal MySQL server ids; these ids must be different for replication to work (or the --replicate-same-server-id option must be used on slave but this does not always make sense; please check the manual before using it).
check the server_id 
find my.cnf not Take effect
vi  /etc/apparmor.d/usr.sbin.mysqld
Add to
/etc/*.cnf rw ,
Solve the problem

but Error again
Last_IO_Error: Got fatal error 1236 from master when reading data from binary log: 'Could not find first log file name in binary log index file'
check the binlog id can't find error

**Comment by qiaofeng1227** [comment]
mysql uuid is same in the master and slave.
It will get  random uuid when mysql start or execute “select uuid();”;but if you set uuid in the file /var/lib/mysql/auto.cnf,it will use the file's uuid.

slove method:
```
sudo rm -f /var/lib/mysql/auto.cnf
```

**Comment by qiaofeng1227** [comment]
### MySQL 主从配置

如果您购买了两台MySQL主从服务器，按照如下步骤可实现所有库、表等数据同步：

1. 使用SSH工具远程登录到MySQL master 服务器，运行命令查看脚本帮助
   ~~~
      [root@iZbp1914ntfd3d0jadprbyZ tools]# cd /data/config
      [root@iZbp1914ntfd3d0jadprbyZ config]# bash master.sh -h

        -h, --help      show help information
        -M, --master-root-password  master mysql root password, Required parameter
        -u, --slave-username   slave mysql username, Required parameter
        -s, --slave-password   slave mysql password, Required parameter
        example:
          bash master.sh -M 123456 -u slave -s 123456
   
   ~~~

2. 根据上面的帮助命令，将-M的参数"123456"替换成数据库root密码([不知道密码？](/zh/stack-accounts.md#mysql))
   ```
      [root@iZbp1914ntfd3d0jadprbyZ config]# bash master.sh -M T9M9bouSVAR9s7m -u slave -s 123456
      master mysql root password is: T9M9bouSVAR9s7m
      slave mysql username is: slave
      slave mysql password is: 123456
      Get parameters success !
      mysql config file update success !
      mysql: [Warning] Using a password on the command line interface can be insecure.
      mysql: [Warning] Using a password on the command line interface can be insecure.
      Create mysql user and set permissive success !
      mysql: [Warning] Using a password on the command line interface can be insecure.
      mysql: [Warning] Using a password on the command line interface can be insecure.
      mysql: [Warning] Using a password on the command line interface can be insecure.
      master log file is: mysql-bin.000008
      master log pos is: 817
      --------------------------------------------
      Congratulations, run complete.
      --------------------------------------------
      [root@iZbp1914ntfd3d0jadprbyZ tools]# 

   ```
   
3. 使用SSH工具远程登录到MySQL slave 服务器，运行命令查看脚本帮助
   ```
      [root@iZbp1dh5vfhy63dps7qt5aZ tools]# cd /data/config
      [root@iZbp1dh5vfhy63dps7qt5aZ config]# bash slave.sh -h

        -h, --help      show help information
        -i, --id        slave server id, Required parameters
        -H, --host      master host ip, Required parameters
        -u, --slave-username   slave mysql username, Required parameter
        -s, --slave-password   slave mysql password, Required parameter
        -S, --slave-root-password   slave mysql root password, Required parameter
        -f, --master-logfile   master binlog logs filename, Required parameter, obtain the value from the master.sh result
        -p, --master-logpos    master binlog logs pos value, obtain the value from the master.sh result
        example:
          bash slave.sh -i 2 -H 192.168.0.1 -u slave -s 123456 -S 123456 -f mysql-bin.000001 -p 214
   
   ```
   
4. 根据上面的帮助命令，将-H的参数"192.168.0.1"替换成master服务器的内网地址，将-S的参数"123456"替换成slave服务器的数据库root密码([不知道密码？](/zh/stack-accounts.md#mysql))，将-f的参数"mysql-bin.000001"替换成master脚本执行后的结果[master log file is]，将将-p的参数"214"替换成master脚本执行后的结果[master log pos]。
   ```
      [root@iZbp1dh5vfhy63dps7qt5aZ config]# bash slave.sh -i 2 -H 172.16.232.184 -u slave -s 123456 -S 1FjTLwlSZz4c2zp -f mysql-bin.000008 -p 817
      slave slave server id is: 2
      master local host is: 172.16.232.184
      slave mysql username is: slave
      slave mysql password is: 123456
      slave mysql root password is: 1FjTLwlSZz4c2zp
      master log file is: mysql-bin.000008
      master log pos is: 817
      Get parameters success !
      MySql config file update success !
      mysql: [Warning] Using a password on the command line interface can be insecure.
      mysql: [Warning] Using a password on the command line interface can be insecure.
      mysql: [Warning] Using a password on the command line interface can be insecure.
      MySql configuration complete
      mysql: [Warning] Using a password on the command line interface can be insecure.
      mysql: [Warning] Using a password on the command line interface can be insecure.
      Slave_IO_Running: Yes
      Slave_SQL_Running: Yes Slave_SQL_Running_State: Replica has read all relay log; waiting for more updates
      --------------------------------------------
      Congratulations, run complete.
      --------------------------------------------
      [root@iZbp1dh5vfhy63dps7qt5aZ tools]# 

   ```

**Comment by qiaofeng1227** [comment]
documentation:
1. https://mariadb.org/database-master-slave-replication-in-the-cloud/
