### ISSUE TITLE
TASK [role_mysql : import MySQL apt key] error on AWS Ubuntu20.04

### ISSUE THREAD

**Issue by zengxc-1996** [websoft9dev/role_mysql#6]
fatal: [47.242.28.31]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key adv --no-tty --keyserver pgp.mit.edu --recv 5072E1F5", "msg": "Error fetching key 5072E1F5 from keyserver: pgp.mit.edu", "rc": 2, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: keyserver receive failed: No data\n", "stderr_lines": ["Warning: apt-key output should not be parsed (stdout is not a terminal)", "gpg: keyserver receive failed: No data"], "stdout": "Executing: /tmp/apt-key-gpghome.gP8qaj8McD/gpg.1.sh --no-tty --keyserver pgp.mit.edu --recv 5072E1F5\n", "stdout_lines": ["Executing: /tmp/apt-key-gpghome.gP8qaj8McD/gpg.1.sh --no-tty --keyserver pgp.mit.edu --recv 5072E1F5"]}

**Comment by chendelin1982** [comment]
`sudo gpg  --keyserver keys.gnupg.net --recv-keys 5072E1F5`  can fetch key successfully

**Comment by chendelin1982** [comment]
use keys.gnupg.net to replace pgp.mit.edu
done
